
development:
  sessions:
    default:
      database: acfun_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: acfun_development
      hosts:
        - localhost:27017
      username: <%= ENV['MONGO_USERNAME'] %>
      password: <%= ENV['MONGO_PASSWORD'] %>
