
development:
  sessions:
    default:
      database: acfun_test
      hosts:
        - localhost:27017
  options:
    allow_dynamic_fields: false

production:
  sessions:
    default:
      database: acfun_development
      hosts:
        - localhost:27017
      username: <%= ENV['MONGO_USERNAME'] %>
      password: <%= ENV['MONGO_PASSWORD'] %>
  options:
    allow_dynamic_fields: false

test:
  sessions:
    default:
      database: acfun_test
      hosts:
        - localhost:27017
